id: P010614
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5096
  title: ཀརྨ་པའི་བཀའ་སྲུང་རྣམས་ཀྱི་བྱུང་བ་དང་བླ་བརྒྱུད།
  author: ''
  volumes:
    b8cfc73850a14ef78409f3db376a9a22:
      image_group_id: I3CN5098
      title: ''
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
