id: I7612676D
legacy_id: P010614
ocr_import_info:
  bdrc_scan_id: W3CN5096
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T09:25:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:51:38.316219+00:00'
last_modified: 2022-09-03 22:51:49.458016
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5096
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5096
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀརྨ་པའི་བཀའ་སྲུང་རྣམས་ཀྱི་བྱུང་བ་དང་བླ་བརྒྱུད།
  author: དཔལ་ཁང་ལོ་ཙཱ་བའི་སྐུ་སྐྱེ་ཀརྨ་གཞན་ཕན་དབང་པོའི་སྡེ།
statistics:
  ocr_word_mean_confidence_index: 0.9671518171298369
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN5098:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5098
      total_pages: 316
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5098.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9671518171298369
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
